
import "./root_style.css";
import { Navbar } from "./components";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <>
      < Navbar />
      <main className="container overflow-hidden">
        {children}
      </main>
    </>

  );
}
